### ISSUE TITLE
Can't be combined with android_alarm_manager

### ISSUE THREAD

**Issue by mrhabibi** [sathish76/flutter_dnd#1]
Hi,

I combine flutter_dnd inside invocation method of [android_alarm_manager](https://pub.dev/packages/android_alarm_manager), but it's failed with error message:

```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method isNotificationPolicyAccessGranted on channel flutter_dnd)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
    <asynchronous suspension>
    #1      FlutterDnd.isNotificationPolicyAccessGranted (package:flutter_dnd/flutter_dnd.dart:26:27)
```

And this is my environment:

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale en-ID)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.43.1)
[√] Connected device (1 available)

• No issues found!
```

Any help would be appreciated.

**Comment by mrhabibi** [comment]
Sorry, false alarm, my whole plugins didn't work too because of [a crash from audiofileplayer plugin](https://github.com/google/flutter.plugins/issues/63), it now works as expected.
